// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5CL8wjFH_hRSiK3JV3BGwFRXyROfReB0',
    appId: '1:583700801246:web:46743aa79abdfc6d0e044f',
    messagingSenderId: '583700801246',
    projectId: 'imc1-f1e93',
    authDomain: 'imc1-f1e93.firebaseapp.com',
    storageBucket: 'imc1-f1e93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9hz_fC1LXB9d3OL_LSCwxwDrVQDHHndg',
    appId: '1:583700801246:android:73ff355e2617c86e0e044f',
    messagingSenderId: '583700801246',
    projectId: 'imc1-f1e93',
    storageBucket: 'imc1-f1e93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1BTN43BkHjyrYEj5rQ3iD75sM3gCXr1A',
    appId: '1:583700801246:ios:b49464afee7740170e044f',
    messagingSenderId: '583700801246',
    projectId: 'imc1-f1e93',
    storageBucket: 'imc1-f1e93.firebasestorage.app',
    iosBundleId: 'com.example.imcSecured',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1BTN43BkHjyrYEj5rQ3iD75sM3gCXr1A',
    appId: '1:583700801246:ios:b49464afee7740170e044f',
    messagingSenderId: '583700801246',
    projectId: 'imc1-f1e93',
    storageBucket: 'imc1-f1e93.firebasestorage.app',
    iosBundleId: 'com.example.imcSecured',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5CL8wjFH_hRSiK3JV3BGwFRXyROfReB0',
    appId: '1:583700801246:web:2da3027828d043540e044f',
    messagingSenderId: '583700801246',
    projectId: 'imc1-f1e93',
    authDomain: 'imc1-f1e93.firebaseapp.com',
    storageBucket: 'imc1-f1e93.firebasestorage.app',
  );
}
